apiVersion: v1
kind: Pod
metadata:
  name: rediness-pod
spec:
  containers:
    - name: app-container
      image: nginx
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5